# Generated by Django 5.0.3 on 2024-03-19 20:01

import login.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', login.models.AccountManager()),
            ],
        ),
    ]
